### PR TITLE
Update to more recent version of clang

### PR DESCRIPTION
**Pull request by ricejasonf**
- Updates the patch file to work with clang trunk
  - Removes custom ActiveTemplateInst and uses the new
    CodeSynthesisContext class
  - Adds the `add_subdirectory(templight)` to the cmake to reduce manual
    steps required to build
  - Updates README.md to reflect cmake subdirectory change
  - The tests don't pass but it appears they weren't passing before
    either

### CODE REVIEW

**Comment by sabel83** [comment]
I tried building it with the current head of `trunk` and got the following error:

```
In file included from llvm/tools/clang/tools/templight/templight_driver.cpp:61:0:
llvm/tools/clang/tools/templight/TemplightAction.h:26:8: error: ‘bool clang::TemplightAction::BeginSourceFileAction(clang::CompilerInstance&, llvm::StringRef)’ marked ‘override’, but does not override
   bool BeginSourceFileAction(CompilerInstance &CI, StringRef Filename) override;
        ^
```

**Comment by ricejasonf** [comment]
Yes it looks like they changed the interface a day later here: https://github.com/llvm-mirror/clang/commit/772553c418344b6943a468b79e043180840eb255

This PR is currently based off of ff4214ddcfab9fd92c15cc01c9c2e17a8f6217ad which it currently the top of my gihub fork: https://github.com/ricejasonf/clang/commits/master

I'll look into updating this.

**Comment by ricejasonf** [comment]
@sabel83 I updated to today's clang/llvm and made a note of the corresponding versions in the commit message since clang/llvm are moving targets. 

This fixes the issue you had with `BeginSourceFileAction`.

**Comment by sabel83** [comment]
Thank you.

**Pull request merged**
