### PR TITLE
Update for clang trunk, and extended template name detection

### PR DESCRIPTION
**Pull request by oktal3700**
Some template names were coming out empty in the protobuf output. After conversion to callgrind format, these were causing assert failures in QCacheGrind. The offenders seemed to be unnamed template parameters, unnamed function parameters, and lambdas with init-captures. I don't know if my fix is the best or proper way, but it works for me.

### CODE REVIEW

**Comment by oktal3700** [comment]
I'm placing this on hold until I collect more information about the bug and the consequences of my fix. You can still cherry-pick the clang trunk update if you want.

**Comment by oktal3700** [comment]
I'm reopening this, having adjusted my fix:

- I no longer read from the `Name` string before the corresponding `raw_string_ostream` has been flushed.
- Instead of `switch`ing on the result of `Decl::getKind`, I now query `isa<T>` for each class of interest `T`. This avoids causing an ICE when for some reason the result of `getKind` apparently doesn't match the real derived type.

As before, this is just my naive solution to a bug, maybe there is a better solution. It's more of a starting point for someone who knows more than me to do a better job. At the very least, a more experienced clang hacker should check that I haven't done anything stupid.

Here's a testcase to demonstrate the bug that I'm fixing:
```cpp
template <bool V, class T = void> struct enable_if { typedef T type; };
template <class T> void invoke(T f) { f(); }

template <bool V = true, class = typename enable_if<V>::type> void a() {}
template <bool V = true, typename enable_if<V, int>::type = 0> void b() {}
template <bool V = true> void c(typename enable_if<V, int>::type = 0) {}
void d() { invoke([]{}); }

void test() { a(); b(); c(); d(); }
```

In the `-Xclang -templight-dump` output you'll see several `name: ''` entries. Unfortunately the bug is replicated in `DefaultTemplateInstCallbacks::GetTemplightEntry`, so the `-templight-dump` output is not affected by my fix. A better fix should address both places. Maybe `clang::NamedDecl::getNameForDiagnostic` should be fixed upstream. Maybe an empty name is actually valid and the real fix should be in QCacheGrind (empty names would collide though, I'm not satisfied by that idea).

**Comment by catskul** [comment]
Is this necessary anymore? Can it be closed?

**Comment by oktal3700** [comment]
I haven't the faintest idea.

**Comment by Szelethus** [comment]
Hi!

I took a look at your patch, and here are my thoughts.

At the end of the day, its fine if a an entity's name is an empty string, theoretically speaking. However, it indeed never hurts to give more information, because dumping a source location is not very friendly. So, I like the idea behind your patch, and it would be awesome to see it landed!

I agree that this should be patched on the clang side. I tinkered with your patch and added it to clang, but haven't quite finished it:

https://github.com/Szelethus/llvm-project/tree/templight-fix

I will add the finishing touches, but its your idea, and your code, and if you have the time, you can submit it on reviews.llvm.org, add me (Szelethus) as reviewer, and I will help to see this through. If you have since moved on, I can also put it up there, with the appropriate disclaimers that this is your work.

So sorry for taking this long to answer!

**Comment by oktal3700** [comment]
@Szelethus I don't have the time, and I have moved on. I agree that it would be great to see it landed, so if you want to do that then that would be awesome, thank you. I don't know if it's possible to add me as a reviewer, I'm not sure if I could give any useful review comments, but I'd be happy to try. If you believe it's my code you're submitting, then fair enough, but I'd say it's more of a team effort. Not least because I've completely forgotten writing it 😄

**Comment by Szelethus** [comment]
https://reviews.llvm.org/D115521

Its up!

**Comment by Szelethus** [comment]
Landed!

**Pull request closed without merging**
